### ISSUE TITLE
faker.name().name() works correctly if I choose "ru" locale, but other methods return result in english.

### ISSUE THREAD

**Issue by mishashin** [DiUS/java-faker#199]
I suppose it's not only for "ru" locale.

**Comment by PascalSchumacher** [comment]
Hi @ mishashin

java-faker only returns locale specific data, if the `locale.yml` file contains any. Otherwise english data is returned.

For example when using java-faker 0.12 you will get russian data if this file: https://github.com/DiUS/java-faker/blob/javafaker-0.12/src/main/resources/ru.yml  contains any for the matching faker method. Otherwise java-faker will fetch the data from this file: https://github.com/DiUS/java-faker/blob/javafaker-0.12/src/main/resources/en.yml

Cheers,
Pascal
