### ISSUE TITLE
Address generation country error when used with locale

### ISSUE THREAD

**Issue by ressec** [DiUS/java-faker#268]
Hello,

First of all, congratulations on this so helpful data generator API.

I found a potential bug when using the **Faker** object to generate addresses using a locale. Let's take an example...

If I use the **Faker** to generate a, let's say, set of french addresses ... it generates:

```
. . .
99 Passage Monsieur-le-Prince 42765 Tours Paraguay
032 Impasse des Lombards 34919 Nîmes Greenland
035 Rue des Panoramas 55636 Pau Macedonia
. . .

```

but the country is wrong, it should be **France** for all of them.

It's the same for all locales.

Regards,
Chris

**Comment by codingricky** [comment]
@ressec There is a problem there which is caused by lack of data for that locale. So all locales will default to the english locale if there is no data specific to that locale. So country will look for French data but when that doesn't exist, it'll use the English one. 

However even in saying that, I don't think the data should return **France** for all of them but rather French names for the countries.

**Comment by shortstacked** [comment]
I wouldn't call it a bug, but it does seem like an unclear implementation.  An entry could be added to the readme file explaining what Faker services are changed depending on locale passed in.
