### ISSUE TITLE
Cleaning Up

### ISSUE THREAD

**Issue by stoffel2107** [DiUS/java-faker#367]
Hey,
I started using Java-Faker and wanted to help improving but i wanted to write issues first so you can decide what you want to have and what i should better not do.

Therefore i will be fixing all issues myself.

With Clean Up i mean bringing every YML file into a structure like the files in the en folder, making it easier to spot missing yml files for a language and append a lagnuages content.

Furthermore i refactored all Implementation Classes into a package called Implementations, as can be seen in my fork.

I thought about switching to an ENUM instead of the EN class but i am not sure if this is necessary or a good idea.

Kind regards

**Comment by codingricky** [comment]
@stoffel2107 with moving yml files around, I try and keep the same structure as https://github.com/stympy/faker this one we can just import those yml files as they're updated. They seem to get way more updates than this project, so that strategy has always made sense imho. 

The EN class, I never really wanted it, I struggled to dynamically generate that list.. like it wouldn't work on Android. In terms of converting it to an Enum... I'm not sure I see the benefit as I don't think they're ever addressed individually... if you think differently, I'd like to understand why you would want to convert it to an enum. 

Thanks!

**Comment by stoffel2107** [comment]
you can have a look tonight. I'm at work but I already moved those files and playing around.
Just because this is the easier way doesn't mean it's the best for us as 'Java-Faker' maybe once we have it running in a second branch and tested it properly we can open an issue at stympies and consider spreading a best practice so updating yml files is easier.

And that is exactly what this is about, making it easier to append to our yml files. But I will keep working in branches so once I have finished I can do both just give you the changes I made according to your structure or give you a test branch so you can have a look at how it works for you.
